@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NiwiZW1haWwiOiJuYXV2YXNsQGdtYWlsLmNvbSIsImlhdCI6MTY2NzE5NzI5NiwiZXhwIjoxNjY3MjA0NDk2fQ.hstSWTp0sfTH9yGz4VLt3Lmu6Ul4heCBZTb1ghsu4sc

//REGISTER
###
POST http://localhost:2000/users/register
Content-Type: application/json

{
    "full_name": "Muhammad Nauval Saiholau",
    "email": "",
    "username": "asdasd",
    "password": "1234",
    "profil_image_url": "aaaaa.com",
    "age": 10,
    "phone_number": 123456
}

//LOGIN
###
POST http://localhost:2000/users/login
Content-Type: application/json

{
    "email": "nauvasl@gmail.com",
    "password": "1234"
}


###
# FOR CHECKING ACCOUNT THAT LOGGED IN
GET http://localhost:2000/getUser
Content-Type: application/json
token: {{token}}

###
PUT http://localhost:2000/users/update/5
Content-Type: application/json
token: {{token}}

{
    "full_name": "Diptya Bagus Sumantry",
    "email": "12@gmail.com",
    "username": "12",
    "profil_image_url": "profil.com",
    "age": 20,
    "phone_number": 08  
}
###
DELETE http://localhost:2000/users/delete/1
token: {{token}}

//Photo
###
POST  http://localhost:2000/photo/createPhoto
Content-Type: application/json
token: {{token}}

{
    "title" : "PHOTO KEDUA",
    "caption": " CEKCEK",
    "poster_image_url": "aaaa.com"
}

###
GET http://localhost:2000/photo/getPhoto
Content-Type: application/json
token: {{token}}

//menampilkan foto authorization sesuai user
###
GET http://localhost:2000/photo/getPhoto/2
Content-Type: application/json
token: {{token}}

###
PUT  http://localhost:2000/photo/updatePhoto/1
Content-Type: application/json
token: {{token}}

{
    "title" : "PHOTO KEDUA Edit",
    "caption": " CEKCEK",
    "poster_image_url": "aaaa.com"
}

###
DELETE http://localhost:2000/photo/deletePhoto/1
token: {{token}}

//Comment
###
POST  http://localhost:2000/comment/createComment
Content-Type: application/json
token: {{token}}

{
    "PhotoId": 11,
    "Comments": "Cekcek"
}

###
GET http://localhost:2000/comment/getComment
token: {{token}}

###
PUT http://localhost:2000/comment/updateComment/14
Content-Type: application/json
token: {{token}}

{
    "Comments": "Edited"
}

###
DELETE  http://localhost:2000/comment/deleteComment/15
token: {{token}}

//Social Media
###
POST  http://localhost:2000/sosmed/createSosmed
Content-Type: application/json
token: {{token}}

{
    "name" : "123", 
    "social_media_url": "Instagram.com"
}

###
GET http://localhost:2000/sosmed/getSosmed
token: {{token}}

###
PUT http://localhost:2000/sosmed/putSosmed/1
Content-Type: application/json
token: {{token}}

{
    "name" : "Facebook", 
    "social_media_url": "Facebook.com"
}

###
DELETE  http://localhost:2000/sosmed/deleteSosmed/1
token: {{token}}
