@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiZW1haWwiOiIxMjM0QGdtYWlsLmNvbSIsImlhdCI6MTY2NzAxMDk1NCwiZXhwIjoxNjY3MDE4MTU0fQ.cV-_aERwe1GYxeTBkjBnplzWE1gMQji5z-xXWYikQMk

//REGISTER
###
POST http://localhost:2000/users/register
Content-Type: application/json

{
    "full_name": "Diptya Bagus Sumantry",
    "email": "1234@gmail.com",
    "username": "1234",
    "password": "1234",
    "profil_image_url": "aaaaa.com",
    "age": 10,
    "phone_number": 12345678901234
}

//LOGIN
###
POST http://localhost:2000/users/login
Content-Type: application/json

{
    "email": "1234@gmail.com",
    "password": "1234"
}


###
GET http://localhost:2000/getUser
Content-Type: application/json
token: {{token}}

###
PUT http://localhost:2000/users/update/6
Content-Type: application/json
token: {{token}}

{
    "full_name": "Diptya Bagus Sumantry",
    "email": "12@gmail.com",
    "username": "12",
    "profil_image_url": "profil.com",
    "age": 10,
    "phone_number": 12   
}
###
DELETE http://localhost:2000/users/delete/5
token: {{token}}

//Photo
###
POST  http://localhost:2000/photo/createPhoto
Content-Type: application/json
token: {{token}}

{
    "title" : "PHOTO KEDUA",
    "caption": " CEKCEK",
    "poster_image_url": "aaaa.com"
}

###
GET http://localhost:2000/photo/getPhoto
Content-Type: application/json
token: {{token}}

//menampilkan foto authorization sesuai user
###
GET http://localhost:2000/photo/getPhoto/15
Content-Type: application/json
token: {{token}}

###
PUT  http://localhost:2000/photo/updatePhoto/15
Content-Type: application/json
token: {{token}}

{
    "title" : "PHOTO KEDUA Sudah di Edit",
    "caption": " CEKCEK",
    "poster_image_url": "aaaa.com"
}

###
DELETE http://localhost:2000/photo/deletePhoto/7
token: {{token}}

//Comment
###
POST  http://localhost:2000/comment/createComment
Content-Type: application/json
token: {{token}}

{
    "PhotoId": 11,
    "Comments": "Cekcek"
}

###
GET http://localhost:2000/comment/get
token: {{token}}

###
PUT http://localhost:2000/comment/updateComment/13
Content-Type: application/json
token: {{token}}

{
    "Comments": "Sudah di Edit"
}

###
DELETE  http://localhost:2000/comment/deleteComment/1
token: {{token}}

//Social Media
###
POST  http://localhost:2000/sosmed/crateSosmed
Content-Type: application/json
token: {{token}}

{
    "name" : "Instagram", 
    "social_media_url": "Instagram.com", 
    "UserId" : 4
}

###
GET http://localhost:2000/sosmed/getSosmed
token: {{token}}

###
PUT http://localhost:2000/sosmed/putSosmed/1
Content-Type: application/json
token: {{token}}

{
    "name" : "Facebook", 
    "social_media_url": "Facebook.com", 
    "UserId" : 4
}

###
DELETE  http://localhost:2000/sosmed/deleteSosmed/1
token: {{token}}
